version: "3.8"

networks:
  default:
    driver: overlay

services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always
  frontend:
    image: yz2297/hotel_reservation
    entrypoint: frontend
    ports:
      - "5000:5000"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always

  profile:
    image: yz2297/hotel_reservation
    entrypoint: profile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  search:
    image: yz2297/hotel_reservation
    entrypoint: search
    ports:
      - "8082:8082"
    depends_on:
      - jaeger
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  geo:
    image: yz2297/hotel_reservation
    entrypoint: geo
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-geo
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  rate:
    image: yz2297/hotel_reservation
    entrypoint: rate
    ports:
      - "8084:8084"
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  recommendation:
    image: yz2297/hotel_reservation
    entrypoint: recommendation
    ports:
      - "8085:8085"
    depends_on:
      - mongodb-recommendation
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  user:
    image: yz2297/hotel_reservation
    entrypoint: user
    ports:
      - "8086:8086"
    depends_on:
      - mongodb-user
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
  reservation:
    image: yz2297/hotel_reservation
    entrypoint: reservation
    ports:
      - "8087:8087"
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always 
  jaeger:
    image: jaegertracing/all-in-one:latest
    entrypoint: "/go/bin/all-in-one-linux --sampling.strategies-file=/etc/jaeger/sampling_strategies.json --memory.max-traces=10000"
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
  memcached-rate:
    image: memcached
    ports:
     - 11212:11211
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    restart: always
  memcached-profile:
    image: memcached
    ports:
     - 11213:11211
    environment:
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_THREADS=4
    logging:
      options:
        max-size: 50m
    restart: always
  memcached-reserve:
    image: memcached
    ports:
     - 11214:11211
    environment:
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_THREADS=4
    logging:
      options:
        max-size: 50m
    restart: always
  mongodb-geo:
    image: mongo:4.4.3
    ports:
      - "27018:27017" 
    volumes:
      - geo:/data/db 
    restart: always
  mongodb-profile:
    image: mongo:4.4.3
    ports:
      - "27019:27017"   
    volumes:
      - profile:/data/db 
    restart: always
  mongodb-rate:
    image: mongo:4.4.3
    ports:
      - "27020:27017"    
    volumes:
      - rate:/data/db
    restart: always
  mongodb-recommendation:
    image: mongo:4.4.3
    ports:
      - "27021:27017"    
    volumes:
      - recommendation:/data/db
    restart: always
  mongodb-reservation:
    image: mongo:4.4.3
    ports:
      - "27022:27017"
    volumes:
      - reservation:/data/db 
    restart: always
  mongodb-user: 
    image: mongo:4.4.3
    ports:
      - "27023:27017"   
    volumes:
      - user:/data/db
    restart: always
volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user: