version: "3.8"

networks:
  default:
    driver: overlay

services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  frontend:
    image: yz2297/hotel_reservation
    entrypoint: frontend
    ports:
      - "5000:5000"
    depends_on:
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  profile:
    image: yz2297/hotel_reservation
    entrypoint: profile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  search:
    image: yz2297/hotel_reservation
    entrypoint: search
    ports:
      - "8082:8082"
    depends_on:
      - jaeger
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  geo:
    image: yz2297/hotel_reservation
    entrypoint: geo
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-geo
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  rate:
    image: yz2297/hotel_reservation
    entrypoint: rate
    ports:
      - "8084:8084"
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  recommendation:
    image: yz2297/hotel_reservation
    entrypoint: recommendation
    ports:
      - "8085:8085"
    depends_on:
      - mongodb-recommendation
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  user:
    image: yz2297/hotel_reservation
    entrypoint: user
    ports:
      - "8086:8086"
    depends_on:
      - mongodb-user
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  reservation:
    image: yz2297/hotel_reservation
    entrypoint: reservation
    ports:
      - "8087:8087"
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    volumes:
      - ./config.json:/go/src/github.com/harlow/go-micro-services/config.json
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  # 高CPU数据库和缓存服务
  mongodb-geo:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  mongodb-profile:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  mongodb-rate:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  mongodb-recommendation:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  mongodb-reservation:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  mongodb-user:
    image: mongo:4.4.3
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == compute

  memcached-profile:
    image: memcached:latest
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  memcached-rate:
    image: memcached:latest
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  memcached-reserve:
    image: memcached:latest
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data

  # Jaeger需要自行补充完整配置
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.type == data